name: "Bug"
description: "Signaler un comportement incorrect"
title: "[BTS-XX] bug : "
labels: ["type: bug", "priority: high"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Explique clairement le problème.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Lancer le script
        2. Charger un fichier log
        3. Observer l’erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environnement
      placeholder: Python 3.11, Ubuntu, GitHub Actions
